name: Docker-Publish-Pipeline

on:
  push:
    branches:
      - main

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t devops-sample-app .

      # Step 5: Tag Image for Docker Hub
      - name: Tag Docker Image
        run: docker tag devops-sample-app ${{ secrets.DOCKER_USERNAME }}/devops-sample-app:v2

      # Step 6: Push Image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-sample-app:v2

      # Step 7: Print success message
      - name: Print Success
        run: echo "Docker image successfully pushed to Docker Hub!"
